######################################################################################################################
# This is a wrapper yml used as a Build Pipeline.. this is using build-template.yml under azure-pipelines-template and 
# running all tasks related to Build process.
######################################################################################################################

# To run pipeline by only using scheduled triggers, you disable PR and continuous integration triggers
# by specifying pr: none and trigger: none in YAML file.
trigger: none
pr: none

# schedules:
# - cron: "56 06 * * *"
#   displayName: Daily midnight build
#   branches:
#     include:
#     - feature/template_enhancement
#   always: true

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

  
variables:
  - template: env-config/common-variables.yml
  - ${{ if eq(variables['Build.SourceBranchName'], 'sbx') }}: # only works if this is sandbox branch
    - group: cfgen2-sm-http-hashi-sbx
    - group: cfgen2-cloudscheduler-sm-http-hashi-sbx
  - ${{ if eq(variables['Build.SourceBranchName'], 'nonprod') }}: # only works if this is nonprod branch
    - group: cloud-function-hashi-npd
    - group: cloud-scheduler-cfgen2-hashi-npd
  - ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}: # only works if this is prod branch
    - group: cfgen2-sm-http-hashi-prd
    - group: cfgen2-cloudscheduler-sm-http-hashi-prd

stages:
  - template: azure-pipelines-template/build-template.yml
    parameters:
      AIR_ID: $(AIR_ID)
      PYTHON_VERSION: $(PYTHON_VERSION)
      pylint_version: $(pylint_version)
      GCP_PROJECT_ID: $(GCP_PROJECT_ID)
      pylint_min_rank: $(pylint_min_rank)
